<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="TestModule_3" Id="{80aeded2-fde7-42a7-be9c-6fe0efe40b0a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TestModule_3
VAR_INPUT
	fbNextStationReleaseHybrid : ReleaseHybrid;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbNextStationReleaseHybrid();]]></ST>
    </Implementation>
    <LineIds Name="TestModule_3">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>